"""Add custom_report_base_name to Scenario

Revision ID: 452e39801c5e
Revises: 5441dc6602d8
Create Date: 2025-05-21 11:24:26.064813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '452e39801c5e'
down_revision = '5441dc6602d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_report_base_name', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_column('custom_report_base_name')

    # ### end Alembic commands ###
