"""Add mapping_target_cell to ScenarioStep

Revision ID: 5441dc6602d8
Revises: 3aa103ee2622
Create Date: 2025-05-18 17:19:09.492578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5441dc6602d8'
down_revision = '3aa103ee2622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_step', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mapping_target_cell', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario_step', schema=None) as batch_op:
        batch_op.drop_column('mapping_target_cell')

    # ### end Alembic commands ###
