"""Initial database structure with core tables.

Revision ID: 584a1d0cad8d
Revises: 
Create Date: 2025-04-16 15:31:05.954656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584a1d0cad8d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultant',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('consultant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultant_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_consultant_username'), ['username'], unique=True)

    op.create_table('report_template',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_table('scenario',
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('megara_url', sa.Text(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=False),
    sa.Column('enable_anomalies', sa.Boolean(), nullable=False),
    sa.Column('email_recipients', sa.Text(), nullable=True),
    sa.Column('upload_path', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('report_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['consultant.user_id'], ),
    sa.ForeignKeyConstraint(['report_template_id'], ['report_template.template_id'], ),
    sa.PrimaryKeyConstraint('scenario_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario')
    op.drop_table('report_template')
    with op.batch_alter_table('consultant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultant_username'))
        batch_op.drop_index(batch_op.f('ix_consultant_email'))

    op.drop_table('consultant')
    # ### end Alembic commands ###
