"""Add anomaly_score to MonitoringResult

Revision ID: 5e2afc33d612
Revises: 452e39801c5e
Create Date: 2025-05-29 20:34:44.644536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e2afc33d612'
down_revision = '452e39801c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anomaly_score', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_result', schema=None) as batch_op:
        batch_op.drop_column('anomaly_score')

    # ### end Alembic commands ###
