"""Remove enable_anomalies field

Revision ID: c4049f395473
Revises: 5e2afc33d612
Create Date: 2025-05-29 23:43:33.848324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4049f395473'
down_revision = '5e2afc33d612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.drop_column('enable_anomalies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_anomalies', sa.BOOLEAN(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
